/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.pa1.p1.app;

import javax.swing.JOptionPane;

/**
 *
 * @author uth
 */
public class FrmDialogos extends javax.swing.JFrame {

    /**
     * Creates new form FrmDialogos
     */
    public FrmDialogos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAnioNacimiento = new javax.swing.JLabel();
        txtAnioNacimiento = new javax.swing.JTextField();
        btnCalcularEdad = new javax.swing.JButton();
        btnPregunta = new javax.swing.JButton();
        btnPreguntaConRespuesta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAnioNacimiento.setText("Anño Nacimiento");

        btnCalcularEdad.setText("Calcular Edad");
        btnCalcularEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularEdadActionPerformed(evt);
            }
        });

        btnPregunta.setText("Preguntar Seguro");
        btnPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntaActionPerformed(evt);
            }
        });

        btnPreguntaConRespuesta.setText("Preguntar Nombre");
        btnPreguntaConRespuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreguntaConRespuestaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblAnioNacimiento)
                        .addGap(37, 37, 37)
                        .addComponent(txtAnioNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPregunta)
                            .addComponent(btnCalcularEdad)
                            .addComponent(btnPreguntaConRespuesta))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnioNacimiento)
                    .addComponent(txtAnioNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnCalcularEdad)
                .addGap(38, 38, 38)
                .addComponent(btnPregunta)
                .addGap(44, 44, 44)
                .addComponent(btnPreguntaConRespuesta)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularEdadActionPerformed
        // TODO add your handling code here:
        try {
            int anioNacimiento = Integer.parseInt(txtAnioNacimiento.getText());
            JOptionPane.showMessageDialog(this, (2020 - anioNacimiento));
        } catch (Exception e) {
            JOptionPane
                    .showMessageDialog(this,
                            "Error al calcular:" + e.getMessage(),
                            "Calculo",
                            JOptionPane.ERROR_MESSAGE
                    );
        }


    }//GEN-LAST:event_btnCalcularEdadActionPerformed

    private void btnPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntaActionPerformed
        // TODO add your handling code here:
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Tiene seguro?");

        System.out.println("respuesta: " + respuesta);

        if (respuesta == JOptionPane.YES_OPTION) {
            JOptionPane.showMessageDialog(this, "Bien por usted");
        } else if (respuesta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(this, "Quiere uno?");
        } else {
            System.out.println("No hizo nada");
        }


    }//GEN-LAST:event_btnPreguntaActionPerformed

    private void btnPreguntaConRespuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreguntaConRespuestaActionPerformed
        // TODO add your handling code here:
        String respuesta=JOptionPane.showInputDialog(this, "¿Cual es tu nombre?");
        JOptionPane.showMessageDialog(this,"Hola "+respuesta);
    }//GEN-LAST:event_btnPreguntaConRespuestaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDialogos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDialogos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcularEdad;
    private javax.swing.JButton btnPregunta;
    private javax.swing.JButton btnPreguntaConRespuesta;
    private javax.swing.JLabel lblAnioNacimiento;
    private javax.swing.JTextField txtAnioNacimiento;
    // End of variables declaration//GEN-END:variables
}
