/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hn.uth.pa1.parcial2.app;

import hn.uth.pa1.parcial2.app.objetos.Vehiculo;
import hn.uth.pa1.parcial2.app.repositorios.VehiculoRepositorio;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Alumno
 */
public class FrmHumanos extends javax.swing.JFrame {

    /**
     * Creates new form FrmHumanos
     */
    //este es el constructor
    public FrmHumanos() {
        initComponents();
        inicializarFormulario();
    }

    public void inicializarFormulario(){    
        try {
            tblHumanos.setModel(FrmHumanosController.getTblHumanos());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Error al llenar la tabla: "+e.toString());
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProbarConexion = new javax.swing.JButton();
        btnGuardarPrueba = new javax.swing.JButton();
        btnPruebaActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnProbarBuscarTodos = new javax.swing.JButton();
        btnProbarBuscarUno = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHumanos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProbarConexion.setText("Probar conexion");
        btnProbarConexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarConexionActionPerformed(evt);
            }
        });

        btnGuardarPrueba.setText("Prueba de insert");
        btnGuardarPrueba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPruebaActionPerformed(evt);
            }
        });

        btnPruebaActualizar.setText("Prueba Actualizar");
        btnPruebaActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPruebaActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Prueba Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnProbarBuscarTodos.setText("Probar buscar Todos");
        btnProbarBuscarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarBuscarTodosActionPerformed(evt);
            }
        });

        btnProbarBuscarUno.setText("Probar buscar uno");
        btnProbarBuscarUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProbarBuscarUnoActionPerformed(evt);
            }
        });

        tblHumanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblHumanos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPruebaActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarPrueba)
                    .addComponent(btnProbarConexion)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProbarBuscarTodos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProbarBuscarUno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnProbarConexion)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarPrueba)
                        .addGap(18, 18, 18)
                        .addComponent(btnPruebaActualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProbarBuscarTodos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnProbarBuscarUno)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProbarConexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarConexionActionPerformed
        // TODO add your handling code here:
        VehiculoRepositorio vr=new VehiculoRepositorio();
        try {
            Connection connection = vr.getConnection();
            
            JOptionPane.showMessageDialog(this,"Conexión establecida");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString());
        }
    }//GEN-LAST:event_btnProbarConexionActionPerformed

    private void btnGuardarPruebaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPruebaActionPerformed
        // TODO add your handling code here:
        VehiculoRepositorio vr=new VehiculoRepositorio();
        try {
            Vehiculo nuevo=new Vehiculo("PDX2020", "Nissan", "Centra", 8080);
            vr.crear(nuevo);
            JOptionPane.showMessageDialog(this,"Exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString());
        }
    }//GEN-LAST:event_btnGuardarPruebaActionPerformed

    private void btnPruebaActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPruebaActualizarActionPerformed
        // TODO add your handling code here:
        VehiculoRepositorio vr=new VehiculoRepositorio();
        try {
            //se necesita el vehiculo pero por temas de tiempo se va a crear uno similar
            Vehiculo nuevo=new Vehiculo("PDX2020", "Nissan", "Centra", 8080);
            
            //aqui se comienza a modificar
            nuevo.setMarca("nueva marca 2020");
            
            vr.actualizar(nuevo);
            JOptionPane.showMessageDialog(this,"Exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString());
        }
    }//GEN-LAST:event_btnPruebaActualizarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        VehiculoRepositorio vr=new VehiculoRepositorio();
        try {
            //se necesita el vehiculo pero por temas de tiempo se va a crear uno similar
            Vehiculo nuevo=new Vehiculo("PDX2020", "Nissan", "Centra", 8080);
            
            //antes de llamar al eliminar, primero se debe obtener
            vr.eliminar(nuevo);
            JOptionPane.showMessageDialog(this,"Exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString());
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnProbarBuscarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarBuscarTodosActionPerformed
        // TODO add your handling code here:
        VehiculoRepositorio vr=new VehiculoRepositorio();
        try {
            
            //antes de llamar al eliminar, primero se debe obtener
            List<Vehiculo> listaRetorna = vr.buscarTodo();
            for (Vehiculo valorTemporal : listaRetorna) {
                System.out.println(valorTemporal);
            }
            
            JOptionPane.showMessageDialog(this,"Exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString());
        }
    }//GEN-LAST:event_btnProbarBuscarTodosActionPerformed

    private void btnProbarBuscarUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProbarBuscarUnoActionPerformed
        // TODO add your handling code here:
        VehiculoRepositorio vr=new VehiculoRepositorio();
        try {
            Vehiculo valorBuscado = vr.buscar("PDX2020");
            
            System.out.println(valorBuscado);
            
            JOptionPane.showMessageDialog(this,"Exito");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,e.toString());
        }
    }//GEN-LAST:event_btnProbarBuscarUnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmHumanos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmHumanos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarPrueba;
    private javax.swing.JButton btnProbarBuscarTodos;
    private javax.swing.JButton btnProbarBuscarUno;
    private javax.swing.JButton btnProbarConexion;
    private javax.swing.JButton btnPruebaActualizar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHumanos;
    // End of variables declaration//GEN-END:variables
}
